Repository overture-stack/ego, pull requests merged in 2019-02, with the labels that each got.

#241 Create endpoint to revoke token for ticket #197.
  src/main/java/bio/overture/ego/controller/TokenController.java
  src/main/java/bio/overture/ego/service/TokenService.java
  src/main/java/bio/overture/ego/service/UserService.java
  src/test/java/bio/overture/ego/token/RevokeTokenTest.java
  src/test/java/bio/overture/ego/utils/TestData.java
Labels: review

#240 Implemented admin role for applications
  src/main/java/bio/overture/ego/model/dto/CreateApplicationRequest.java
  src/main/java/bio/overture/ego/model/dto/CreateUserRequest.java
  src/main/java/bio/overture/ego/model/dto/UpdateApplicationRequest.java
  src/main/java/bio/overture/ego/model/dto/UpdateUserRequest.java
  src/main/java/bio/overture/ego/model/entity/Application.java
  src/main/java/bio/overture/ego/model/entity/User.java
  src/main/java/bio/overture/ego/model/enums/AccessLevel.java
  src/main/java/bio/overture/ego/model/enums/ApplicationType.java
  src/main/java/bio/overture/ego/model/enums/Fields.java
  src/main/java/bio/overture/ego/model/enums/JavaFields.java
  src/main/java/bio/overture/ego/model/enums/SqlFields.java
  src/main/java/bio/overture/ego/model/enums/UserType.java
  src/main/java/bio/overture/ego/reactor/receiver/UserReceiver.java
  src/main/java/bio/overture/ego/security/SecureAuthorizationManager.java
  src/main/java/bio/overture/ego/service/AbstractBaseService.java
  src/main/java/bio/overture/ego/service/TokenService.java
  src/main/java/bio/overture/ego/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/flyway/sql/V1_8__application_types.sql
  src/test/java/bio/overture/ego/controller/UserControllerTest.java
  src/test/java/bio/overture/ego/service/TokenStoreServiceTest.java
  src/test/java/bio/overture/ego/service/UserServiceTest.java
  src/test/java/bio/overture/ego/token/RevokeTokenTest.java
  src/test/java/bio/overture/ego/utils/EntityGenerator.java
  src/test/java/bio/overture/ego/utils/TestData.java
Labels: in progress, review

#245 Create an endpoint to list tokens for given user.
  src/main/java/bio/overture/ego/controller/TokenController.java
  src/main/java/bio/overture/ego/model/dto/TokenResponse.java
  src/main/java/bio/overture/ego/service/TokenService.java
  src/test/java/bio/overture/ego/token/ListTokenTest.java
Labels: review

#244 Feature/policytests
  src/main/java/bio/overture/ego/controller/PolicyController.java
  src/main/java/bio/overture/ego/model/dto/GenericResponse.java
  src/main/java/bio/overture/ego/repository/PermissionRepository.java
  src/main/java/bio/overture/ego/repository/queryspecification/GroupPermissionSpecification.java
  src/main/java/bio/overture/ego/repository/queryspecification/UserPermissionSpecification.java
  src/main/java/bio/overture/ego/service/GroupPermissionService.java
  src/main/java/bio/overture/ego/service/UserPermissionService.java
  src/test/java/bio/overture/ego/controller/PolicyControllerTest.java
  src/test/java/bio/overture/ego/service/PolicyServiceTest.java
  src/test/java/bio/overture/ego/utils/EntityGenerator.java
Labels: in progress, review

#237 OAuth2 Refactoring
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/bio/overture/ego/config/AuthConfig.java
  src/main/java/bio/overture/ego/config/CorsProperties.java
  src/main/java/bio/overture/ego/config/OAuth2ClientConfig.java
  src/main/java/bio/overture/ego/config/SecureServerConfig.java
  src/main/java/bio/overture/ego/controller/AuthController.java
  src/main/java/bio/overture/ego/provider/facebook/FacebookTokenService.java
  src/main/java/bio/overture/ego/provider/google/GoogleTokenService.java
  src/main/java/bio/overture/ego/provider/linkedin/LinkedInOAuthService.java
  src/main/java/bio/overture/ego/security/CorsFilter.java
  src/main/java/bio/overture/ego/security/GithubUserInfoTokenServices.java
  src/main/java/bio/overture/ego/security/LinkedInUserInfoTokenServices.java
  src/main/java/bio/overture/ego/security/OAuth2ClientResources.java
  src/main/java/bio/overture/ego/security/OAuth2SsoFilter.java
  src/main/java/bio/overture/ego/security/OAuth2UserInfoTokenServices.java
  src/main/java/bio/overture/ego/service/ApplicationService.java
  src/main/java/bio/overture/ego/service/UserService.java
  src/main/resources/application.yml
Labels: in progress, review

#248 Minor fixes regarding applicationType enum.
  src/main/java/bio/overture/ego/model/dto/CreateApplicationRequest.java
  src/test/java/bio/overture/ego/service/TokenStoreServiceTest.java
  src/test/java/bio/overture/ego/utils/EntityGenerator.java
  src/test/java/bio/overture/ego/utils/TestData.java
Labels: in progress, review

#253 Add unit test for deleteUser endpoint.
  src/test/java/bio/overture/ego/controller/UserControllerTest.java
Labels: review

#254 Change return type to Group json and format UserControllerTest.
  src/main/java/bio/overture/ego/controller/PolicyController.java
  src/test/java/bio/overture/ego/controller/PolicyControllerTest.java
  src/test/java/bio/overture/ego/controller/UserControllerTest.java
Labels: review

#259 Fix cors
  src/main/java/bio/overture/ego/config/AuthConfig.java
  src/main/java/bio/overture/ego/config/CorsProperties.java
  src/main/java/bio/overture/ego/config/SecureServerConfig.java
  src/main/java/bio/overture/ego/controller/PolicyController.java
  src/main/java/bio/overture/ego/security/CorsFilter.java
  src/main/java/bio/overture/ego/security/GithubUserInfoTokenServices.java
  src/main/java/bio/overture/ego/security/LinkedInUserInfoTokenServices.java
  src/main/java/bio/overture/ego/security/OAuth2SsoFilter.java
  src/main/resources/application.yml
  src/main/resources/flyway/sql/V1_8__application_types.sql
Labels: in progress, review

#264 Use pre established redirect url
  src/main/java/bio/overture/ego/security/OAuth2ClientResources.java
Labels: in progress, review

#266 Fixed getting 403 forbidden on public_key endpoint.
  src/main/java/bio/overture/ego/config/SecureServerConfig.java
  src/main/java/bio/overture/ego/security/JWTAuthorizationFilter.java
Labels: review

#268 Changed log.error to log.info.
  src/main/java/bio/overture/ego/service/ApplicationService.java
Labels: review

#270 Changed Token.java - isRevoked to be updatable true.
  src/main/java/bio/overture/ego/model/entity/Token.java
Labels: review

#274 Expose ego token verify endpoint
  src/main/java/bio/overture/ego/config/SecureServerConfig.java
Labels: SP:1, review
